In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

In [3]:
# importing a data set
df = sns.load_dataset("taxis")
df = df[["color", "payment"]]

In [4]:
# Split the data
x_train, x_test = train_test_split(df, test_size=0.2)
x_train.head(), x_test.head()

(       color      payment
 5866   green  credit card
 986   yellow  credit card
 4714  yellow  credit card
 6027   green  credit card
 4024  yellow  credit card,
        color      payment
 2675  yellow  credit card
 6265   green  credit card
 4656  yellow  credit card
 6159   green  credit card
 2423  yellow         cash)

In [5]:
# Making a ordinal encoding for input columns
ordin = OrdinalEncoder()  # categories =
ordin.fit(x_train)
ordin.categories_

[array(['green', 'yellow'], dtype=object),
 array(['cash', 'credit card', nan], dtype=object)]

In [6]:
ordin.transform(x_train)
ordin.transform(x_test)

array([[1., 1.],
       [0., 1.],
       [1., 1.],
       ...,
       [1., 1.],
       [1., 1.],
       [1., 1.]])

<h1> Label and Ordinal encoding Both</h1>

In [9]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [10]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day26-ordinal-encoding/customer.csv"
)
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [11]:
df = df.iloc[:, 2:]
df.head(2)

review education purchased
0  Average    School        No
1     Poor        UG        No

In [20]:
x_train, x_test, y_train, y_test = train_test_split(
    df.iloc[:, 0:-1], df.iloc[:, -1], test_size=0.2
)

In [21]:
x_train.head(), y_train.head()

(     review education
 24  Average        PG
 21  Average        PG
 17     Poor        UG
 47     Good        PG
 10     Good        UG,
 24    Yes
 21     No
 17    Yes
 47    Yes
 10    Yes
 Name: purchased, dtype: object)

In [24]:
# OrdinalEncoding
oe = OrdinalEncoder(categories=[["Poor", "Average", "Good"], ["School", "UG", "PG"]]) 
oe.fit(x_train)
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [26]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [28]:
# x_train, x_test

In [30]:
# LabelEncoding
lbl = LabelEncoder()
lbl.fit(y_train)
lbl.classes_

array(['No', 'Yes'], dtype=object)

In [32]:
y_train = lbl.transform(y_train)
y_test = lbl.transform(y_test)

In [34]:
y_train, y_test

(array([1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0]),
 array([1, 1, 0, 1, 0, 0, 0, 1, 1, 1]))

<h2>Encoded columns</h2>

In [55]:
for i in range(0, len(x_train)):
    print(f'{x_train[i].tolist()} : {y_train[i].tolist()}')

[1.0, 2.0] : 1
[1.0, 2.0] : 0
[0.0, 1.0] : 1
[2.0, 2.0] : 1
[2.0, 1.0] : 1
[2.0, 0.0] : 0
[2.0, 1.0] : 1
[2.0, 1.0] : 1
[2.0, 0.0] : 0
[0.0, 1.0] : 0
[1.0, 1.0] : 1
[1.0, 0.0] : 0
[0.0, 0.0] : 1
[2.0, 2.0] : 1
[0.0, 2.0] : 0
[0.0, 0.0] : 0
[1.0, 1.0] : 0
[0.0, 2.0] : 0
[1.0, 1.0] : 0
[2.0, 0.0] : 0
[0.0, 1.0] : 1
[1.0, 1.0] : 1
[1.0, 0.0] : 0
[0.0, 2.0] : 1
[0.0, 2.0] : 1
[1.0, 1.0] : 0
[2.0, 0.0] : 0
[0.0, 1.0] : 0
[0.0, 2.0] : 1
[1.0, 2.0] : 1
[1.0, 1.0] : 0
[0.0, 2.0] : 0
[2.0, 0.0] : 0
[2.0, 1.0] : 0
[2.0, 2.0] : 1
[0.0, 2.0] : 0
[0.0, 2.0] : 1
[1.0, 0.0] : 0
[2.0, 2.0] : 1
[2.0, 2.0] : 0
