In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
from sklearn.datasets import load_iris

In [28]:
df = load_iris(return_X_y=True)

In [29]:
df1 = pd.DataFrame(df[0])
df2 = pd.DataFrame(df[1])

In [33]:
df1

,0,1,2,3
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [66]:
li = []
for i in range(len(df1)):
    lis = []
    for j in range(len(df1)):
        if i != j:
            lis.append(np.sqrt(np.sum(df1.iloc[i] - df1.iloc[j])**2))
    li.append(lis)

In [67]:
min_values = []
no_of_val = 5
for i in range(len(df1)):
    min_values.append(np.argsort(li[i])[:no_of_val])

In [68]:
min_values

[array([38,  3, 27, 39,  6]),
 array([44,  1, 34,  8,  2]),
 array([ 2, 21, 46, 44,  1]),
 array([21, 46,  2, 44, 11]),
 array([27,  0, 38, 16, 23]),
 array([17, 59, 32, 92, 56]),
 array([29, 28, 33,  8, 34]),
 array([39, 36,  0, 38, 10]),
 array([37, 41, 11, 12,  3]),
 array([34,  6, 29, 28, 33]),
 array([31, 30, 19, 42, 47]),
 array([36,  7, 48, 39, 38]),
 array([ 3, 21, 46,  2, 41]),
 array([40,  8, 37, 41, 12]),
 array([43, 32, 15,  5, 31]),
 array([97, 56, 92, 59, 17]),
 array([31, 43, 14, 10, 32]),
 array([23,  4, 27,  0, 38]),
 array([59, 92,  5, 56, 97]),
 array([45, 20, 47, 42, 19]),
 array([30, 42, 47, 20, 45]),
 array([47, 42, 45, 20, 19]),
 array([ 3, 46,  2, 44, 12]),
 array([35, 19, 45, 21, 47]),
 array([17,  4, 27,  0, 38]),
 array([28, 33, 48, 29,  6]),
 array([26, 35, 24, 17, 23]),
 array([26, 35, 24, 17, 23]),
 array([ 4,  0, 38, 17, 24]),
 array([33, 29,  6, 25,  9]),
 array([29, 33,  6,  9, 34]),
 array([20, 42, 47, 21, 45]),
 array([10, 16, 31, 20, 42]),
 array([ 5

In [83]:
def predict(values):
    pred_li = []
    for i in range(len(values)):
        pred_li.append(np.max(df2.iloc[values[i]]))
    return pred_li

In [84]:
predict(min_values)

[np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.in

In [87]:
from sklearn.metrics import confusion_matrix

In [89]:
confusion_matrix(df2, predict(min_values))

array([[46,  4,  0],
       [ 0, 22, 28],
       [ 0,  2, 48]])